app = "wexa-workers"
primary_region = "iad"

[build]

[env]
  ENVIRONMENT = "production"
  EMAIL_FROM = "noreply@wexa.ai"
  RESEND_API_KEY = ""
  ACCESS_TOKEN_EXPIRE_MINUTES = "15"
  REFRESH_TOKEN_EXPIRE_DAYS = "7"

[processes]
  worker = "celery -A app.workers.celery_app.celery_app worker -Q ingestion,celery -c 2 --loglevel=info"
  beat = "celery -A app.workers.celery_app.celery_app beat --loglevel=info"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
